name: data
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRq2h-z2nr3R6HdpCfV7kPvLbJQqXELptnIC8v5r4cISNouwYgz49WAX07M6agyQZlIDRZAEjbDQt6z/pub?gid=0&single=true&output=csv' 
          downloaded_filename: google-sheet.csv
